# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target '01-AFNetworkingDemo' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

pod 'AFNetworking', '~> 3.0'
end

target '01-AFNetworkingDemoTests' do

end

target '01-AFNetworkingDemoUITests' do

end

